services:
  # PostgreSQL database
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD

  # Database management interface
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080

  # Keycloak setup
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # Persisting Keycloak data using a named volume called keycloak-data
    # This ensures that data isn't lost when the container restarts
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - start-dev       # Launching Keycloak in development mode (used for local dev/tests), simplifies setup
      - --db=dev-file   # Using an in-memory file-based database suitable for testing/development

# Declaring a docker named volume: keycloak-data
volumes:
  keycloak-data:
    driver: local
